---
- hosts: fedora-lab
  become: true
  tasks:
  ## add (present) or renove (absent) a user
  - name: Usuarios Nagios para Fedora
    user:
      name: nagios
      state: present
      shell: /bin/bash
      password: nagios00
      comment: "Usuario Nagios"
  - name: Check users
    shell:
      cmd: id nagios
