---
- hosts: all
  become: true
  tasks:
  ## add (present) or renove (absent) a user
  - name: Usuario para Fedora lab
    user:
      name: "{{ usuario }}"
      state: "{{ estado }}"
      shell: /bin/bash
      password: "{{ password }}"
      comment: "Usuario"
  - name: Check users
    shell:
      cmd: id "{{ usuario }}"
